manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: janpfischer
      url-base: https://github.com/janpfischer
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0.3.0
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    # - name: prospector-zmk-module
    #   remote: badjeff 
    #   revision: main 
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: 0.1.1
  self:
    path: config
